# Generated by Django 4.0.3 on 2022-08-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0004_automobilevo_import_href'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesrecord',
            name='price',
            field=models.CharField(max_length=10),
        ),
    ]
