# Generated by Django 4.0.3 on 2022-08-02 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='reason',
            field=models.CharField(max_length=100),
        ),
    ]
