# Generated by Django 4.0.3 on 2022-08-05 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.ForeignKey(default='Scheduled', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='services', to='service_rest.status'),
        ),
    ]
